import PDFDocument from 'pdfkit';
import { LogSource } from '../../core/logging/log-sources.js';
import type { Logger, ScopedLogger } from '../../core/logging/logger.js';
import type { Cell } from '../emandi/emandi.types.js';
import type { GatepassPayload } from './file.types.js';

export class GatepassRenderer {
  private readonly margin = 36;
  private readonly logoPath = new URL('../../assets/logo_emandi.png', import.meta.url);
  private readonly regularFontPath = new URL('../../assets/anek-deva-regular.ttf', import.meta.url);
  private readonly boldFontPath = new URL('../../assets/anek-deva-bold.ttf', import.meta.url);
  private readonly logger: ScopedLogger;

  constructor({ logger }: { logger: Logger }) {
    this.logger = logger.for(LogSource.File);
  }

  generate = async (payload: GatepassPayload): Promise<Buffer> => this.generatePdf((document) => this.render(document, payload));

  private render = (document: PDFKit.PDFDocument, payload: GatepassPayload): void => {
    const { width, y } = this.drawHeader(document, payload);
    let nextY = this.drawTable(document, this.infoRows(payload), this.margin, y, this.scale([12, 12, 19, 19, 19, 19], width)) + 12;
    nextY = this.drawTable(document, [
      [this.header('गेटपास प्राप्त कर्ता फर्म का नाम व पता'), this.header('परिवहन का साधन और वाहन संख्या'), this.header('निर्दिष्ट कृषि उत्पादन का विवरण'), this.header('क्रेता फर्म का नाम व पता'), this.header('क्रेता व्यापारी से संबंधित मंडी समिति का नाम')],
      [this.value(payload.trader_name), this.value(`${payload.vehicle}\n${payload.vehicle_no}`), { nested: [['नाम', 'किस्म', 'बण्डल की संख्या', 'वजन', 'माप'], [payload.crop_name_hi, payload.crop_type, payload.bundle_no, payload.crop_weight, payload.qty_parameter || '']] }, this.value(payload.kreta_mandiName || payload.kreta_mandi), this.value('')]
    ], this.margin, nextY, this.scale([180, 80, 230, 190, 70], width));
    nextY += 12;
    nextY = this.drawTable(document, [[this.label('Latitude'), this.value(payload.latitude), this.label('Longitude'), this.value(payload.longitude), this.label('टैगिंग का दिनांक'), this.value(payload.taggingDate), this.label('वाहन संख्या'), this.value(payload.vehicle_no)]], this.margin, nextY, this.scale([1, 1, 1, 1, 1, 1, 1, 1], width));
    nextY += 12;
    nextY = this.drawTable(document, [[this.label('गंतव्य स्थान पर पहुँचने का अनुमानित समय'), { parts: [payload.dateofdestination, `(अनुमानित समय - ${payload.estimated_travel_time}) (औसत गति - ${payload.avg_speed} क.मी / घंटा)`], bold: true }]], this.margin, nextY, this.scale([2, 5], width));
    const notesY = nextY + 14;
    this.drawAutoGeneratedLabel(document, notesY);
    this.drawContentBorder(document, notesY + 28);
    this.drawNotes(document, notesY + 34);
  };

  private drawHeader = (document: PDFKit.PDFDocument, payload: GatepassPayload): { width: number; y: number } => {
    const width = document.page.width - this.margin * 2;
    const imageSize = 90;
    const textX = this.margin + imageSize + 10;
    const textWidth = width - 2 * (imageSize + 10);
    document.rect(6, 6, document.page.width - 12, document.page.height - 12).lineWidth(0.6).strokeColor('#000').stroke();
    document.image(this.logoPath.pathname, this.margin, this.margin, { fit: [imageSize, imageSize] });
    document.image(this.decodeDataUrl(payload.qr), document.page.width - this.margin - imageSize, this.margin, { fit: [imageSize, imageSize] });
    const heading = 'कृषि उत्पादन मंडी समिति ';
    const headingWidth = document.font('AnekDevanagariRegular').fontSize(10).widthOfString(heading);
    const mandi = 'सादाबाद';
    const mandiWidth = document.font('AnekDevanagariBold').fontSize(10).widthOfString(mandi);
    const headingX = textX + (textWidth - headingWidth - mandiWidth) / 2;
    document.font('AnekDevanagariRegular').fontSize(10).text(heading, headingX, this.margin, { lineBreak: false });
    document.font('AnekDevanagariBold').fontSize(10).text(mandi, headingX + headingWidth, this.margin, { lineBreak: false });
    document.font('AnekDevanagariRegular').fontSize(10).text('[ प्रपत्र संख्या-5 (क) ]', textX, this.margin + 18, { width: textWidth, align: 'center' });
    document.font('AnekDevanagariRegular').fontSize(10).text('गेटपास', textX, this.margin + 36, { width: textWidth, align: 'center' });
    return { width, y: this.margin + imageSize + 4 };
  };

  private infoRows = (payload: GatepassPayload): Cell[][] => {
    const values: Array<[string, string | undefined]> = [
      ['पुस्तक संख्या', payload.book_number], ['गेटपास संख्या', payload.serial_number], ['आवेदन संख्या (यूनिक कोड)', payload.id],
      ['जारी करने का दिनांक', payload.dateofissue], ['जारी करने का समय', payload.timeofissue], ['संलग्न प्रपत्र-9 की संख्या', payload.nine_r_id],
      ['दिनांक', this.formatDate(payload.dateofissue)], ['गंतव्य की दूरी (KM)', payload.dist_todestination], ['सीमांत गढ़ केंद्र का नाम', payload.home_center],
      ['कोड', payload.center_code], ['उत्पाद का नाम', `${payload.crop_name_hi} (${payload.crop_name})`], ['वजन (कुंतल में)', payload.crop_weight]
    ];
    const rows: Cell[][] = [];
    for (let index = 0; index < values.length; index += 3) rows.push(values.slice(index, index + 3).flatMap(([label, value]) => [{ text: label, align: 'center' }, { text: value || '', bold: true }]));
    return rows;
  };

  private drawNotes = (document: PDFKit.PDFDocument, y: number): void => {
    document.font('AnekDevanagariBold').fontSize(9).fillColor('#ff0000');
    ['नोट :', 'गंतव्य स्थान तक पहुंचने की दूरी 50 किमी (0-50 किमी) है तो पहुंचने का समय 4 घंटा अधिकतम होगा।', 'गंतव्य स्थान तक पहुंचने की दूरी 50-100 किमी है तो पहुंचने का समय 8 घंटा अधिकतम होगा।', 'गंतव्य स्थान तक पहुंचने की दूरी 100-200 किमी है तो पहुंचने का समय 16 घंटा अधिकतम होगा।', 'गंतव्य स्थान तक पहुंचने की दूरी 200-500 किमी है तो पहुंचने का समय 28 घंटा अधिकतम होगा।', 'गंतव्य स्थान तक पहुंचने की दूरी 500 किमी से अधिक है तो पहुंचने का समय 48 घंटा अधिकतम होगा।'].forEach((text, index) => document.text(text, this.margin, y + index * 16, { width: document.page.width - this.margin * 2 }));
    document.fillColor('#000');
  };

  private drawAutoGeneratedLabel = (document: PDFKit.PDFDocument, y: number): void => { document.font('AnekDevanagariBold').fontSize(9).fillColor('#ff0000').text('Auto Generated Gatepass', this.margin, y, { width: document.page.width - this.margin * 2 }); };

  private drawContentBorder = (document: PDFKit.PDFDocument, bottom: number): void => {
    document.rect(12, 12, document.page.width - 24, bottom - 12).lineWidth(0.6).strokeColor('#ff0000').stroke();
  };

  private drawTable = (document: PDFKit.PDFDocument, rows: Cell[][], x: number, y: number, widths: number[]): number => {
    rows.forEach((row) => {
      let column = 0;
      const laidOut = row.map((cell) => { const span = cell.span || 1; const width = widths.slice(column, column + span).reduce((sum, value) => sum + value, 0); const result = { cell, x: x + widths.slice(0, column).reduce((sum, value) => sum + value, 0), width }; column += span; return result; });
      const height = Math.max(...laidOut.map(({ cell, width }) => this.cellHeight(document, cell, width)));
      laidOut.forEach(({ cell, x: cellX, width }) => this.drawCell(document, cell, cellX, y, width, height));
      y += height;
    });
    return y;
  };

  private drawCell = (document: PDFKit.PDFDocument, cell: Cell, x: number, y: number, width: number, height: number): void => {
    if (cell.fill) document.save().fillColor(cell.fill).rect(x, y, width, height).fill().restore();
    document.rect(x, y, width, height).lineWidth(0.6).strokeColor('#ccc').stroke();
    if (cell.nested) return void this.drawNested(document, cell.nested, x, y, width, height);
    if (cell.parts) {
      let textY = y + 4;
      cell.parts.forEach((part, index) => {
        document.font(index ? 'AnekDevanagariRegular' : 'AnekDevanagariBold').fontSize(8.5).text(part, x + 2, textY, { width: width - 4, align: 'left' });
        textY += document.heightOfString(part, { width: width - 8 }) + 2;
      });
      return;
    }
    document.font(cell.bold ? 'AnekDevanagariBold' : 'AnekDevanagariRegular').fontSize(cell.size || 8.5).text(cell.text || '', x + 2, y + 2, { width: width - 4, align: 'left' });
  };

  private drawNested = (document: PDFKit.PDFDocument, rows: string[][], x: number, y: number, width: number, height: number): void => {
    const columnWidths = [0.9, 1, 1.4, 1, 0.7];
    const rowHeight = height / rows.length;
    rows.forEach((row, rowIndex) => row.forEach((text, column) => {
      const cellX = x + columnWidths.slice(0, column).reduce((sum, value) => sum + value, 0) * width / 5;
      const columnWidth = (columnWidths[column] || 0) * width / 5;
      const cellY = y + rowIndex * rowHeight;
      if (column || rowIndex) document.moveTo(cellX, y).lineTo(cellX, y + height).lineWidth(0.6).strokeColor('#ccc').stroke();
      if (rowIndex) document.moveTo(x, cellY).lineTo(x + width, cellY).lineWidth(0.6).strokeColor('#ccc').stroke();
      document.font('AnekDevanagariBold').fontSize(8.5).text(text, cellX + 2, cellY + 2, { width: columnWidth - 4, align: 'left', lineBreak: false });
    }));
  };

  private cellHeight = (document: PDFKit.PDFDocument, cell: Cell, width: number): number => {
    if (cell.nested) return Math.max(40, cell.nested.length * 24);
    document.font(cell.bold ? 'AnekDevanagariBold' : 'AnekDevanagariRegular').fontSize(cell.size || 8.5);
    if (cell.parts) return cell.parts.reduce((height, part) => height + document.heightOfString(part, { width: width - 4 }) + 2, 4);
    return document.heightOfString(cell.text || '', { width: width - 4 }) + 4;
  };
  private label = (text: string): Cell => ({ text, align: 'left' });
  private value = (text: string | undefined): Cell => ({ text: text || '', bold: true, align: 'left' });
  private header = (text: string, span?: number): Cell => ({ text, ...(span ? { span } : {}), bold: true, align: 'left', fill: '#fafafa', size: 8.5 });
  private center = (text: string | undefined): Cell => ({ text: text || '', bold: true, align: 'left' });
  private scale = (values: number[], width: number): number[] => { const factor = width / values.reduce((sum, value) => sum + value, 0); return values.map((value) => value * factor); };
  private decodeDataUrl = (value: string): Buffer => Buffer.from(value.split(',')[1] || value, 'base64');
  private formatDate = (value: string): string => { const match = value.match(/^(\d{4})-(\d{2})-(\d{2})/); return match ? `${match[3]}/${match[2]}/${match[1]}` : value; };

  private generatePdf = async (draw: (document: PDFKit.PDFDocument) => void): Promise<Buffer> => {
    this.logger.info('Rendering Gatepass Pdf...');
    const document = new PDFDocument({ size: 'A4', layout: 'landscape', margin: this.margin });
    document.registerFont('AnekDevanagariRegular', this.regularFontPath.pathname);
    document.registerFont('AnekDevanagariBold', this.boldFontPath.pathname);
    const chunks: Buffer[] = [];
    document.on('data', (chunk: Buffer) => chunks.push(chunk));
    const completed = new Promise<Buffer>((resolve, reject) => { document.on('end', () => resolve(Buffer.concat(chunks))); document.on('error', reject); });
    draw(document);
    document.addPage();
    draw(document);
    document.end();
    return completed;
  };
}
